---
title: Effectiveness of antifungal treatments during chytridiomycosis epizootics in populations of an endangered frog
output:
  bookdown::pdf_document2:
    keep_tex: true
    toc: false
    includes:
      in_header: header.sty
fontsize: 12pt
csl: ecology.csl
bibliography: bibliography.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

\linenumbers

\begin{abstract}
TO BE ADDED

\bigskip
\noindent \textbf{Key words}: antifungal treatment; \textit{Batrachochytrium dendrobatidis}; host-pathogen dynamics; mark-recapture; mountain yellow-legged frog; probiotic; \textit{Rana sierrae}; survival.

\end{abstract}

# Introduction
Emerging infectious diseases are increasingly common in wildlife (Daszak et al. 2000), often due to anthropogenic changes in the ecology of the host or pathogen.
Impacts of disease on wildlife can be severe, including long-term population decline and even extinction, with far-reaching effects on species, communities, and ecosystems (Ostfeld et al. 2010, Scheele et al. 2019).
Diseases of wildlife can also spill over to humans and domestic animals (Daszak et al. 2000). Collectively, these impacts of emerging wildlife diseases have significant consequences to global biodiversity and public health (Daszak et al. 2000). 
As such, the ability to control diseases in wildlife is critically important, but disease management is often difficult because wildlife diseases are relatively poorly described, many fewer intervention measures (e.g., vaccines) are available than for humans, and free ranging wildlife are inherently difficult to study and treat. As a result, available management strategies are mostly insufficient to mitigate the destructive effects of disease on wildlife.



