---
title: "Describe results of LeConte CMR surveys: 2016-2018"
output: none
---

Add required packages
```{r message = FALSE}
library(tidyverse)
library(readr)
```

Read in data
```{r message = FALSE}
cmr1 <- "../data/clean/captures_leconte_20152018.csv" %>% read_csv %>% as_tibble()
cmr1 <- cmr1 %>% mutate(pit_tag_id = as.character(pit_tag_id))
```

Number of frogs captured: 2016-2018
```{r}
cmr2 <- cmr1 %>% filter(capture_date > "2016-01-01")
cmr2 %>% tally()
```

Number of unique indivual frogs captured: 2016-2018
```{r}
cmr2 %>% distinct(pit_tag_id) %>% tally()
```

Number of unique individuals captured by basin
```{r}
cmr2 %>% group_by(location) %>% distinct(pit_tag_id) %>% tally()
```

Number of unique individuals captured by treatment category

```{r}
cmr2 %>% group_by(category) %>% distinct(pit_tag_id) %>% tally()
cmr2 %>% group_by(location, category) %>% distinct(pit_tag_id) %>% tally()
```

Number of indivuals that moved between the upper and lower basins: 2015-2018
```{r}
move <- cmr1 %>% group_by(pit_tag_id) %>% 
  summarize(basin_count = n_distinct(location)) %>% 
  filter(basin_count > 1)
```

More details about individuals that moved between basins
```{r}
cmr1 %>% inner_join(move, by = c("pit_tag_id")) %>% 
  select(pit_tag_id, site_id, capture_date, location, category) %>% 
  arrange(pit_tag_id, capture_date) %>% View()
```






